using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace AzureDevOpsTeamMembersVelocity.Data
{
    /// <summary>
    /// DbContext clas used when the environment variable USE_IDENTITY is set to true. This class as been auto generated by 
    /// scafolding tool.
    /// </summary>
    public class IdentityContext : IdentityDbContext<IdentityUser>
    {
        /// <summary>
        /// Constructor use to instanciate a IdentityContext
        /// </summary>
        /// <param name="options"></param>
        public IdentityContext(DbContextOptions<IdentityContext> options)
            : base(options)
        {
        }
    }
}
