name: AzureDevOpsTeamMembersVelocity-Image

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

env:
  REGISTRY_HOSTNAME: erabliereapi
  IMAGE_NAME: azuredevopsteammembersvelocity
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Login into acr
      - name: Login into ACR
        run: echo ${{ secrets.registryPassword }} | docker login -u ${{ secrets.registryUsername }} --password-stdin

      # Build the image
      - name: Docker build
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .
        
      # Tag the images
      - name: Docker tag
        run: docker tag $IMAGE_NAME:$IMAGE_TAG $REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG

      # Push the image
      - name: Docker push
        run: docker push $REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG
